---
- name: Install apache
  ansible.builtin.yum:
    name: httpd
    state: present
- name: Start apache
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes
- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
- name: Add apache on FW
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
- name: Template a file 
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html.j2

