---
- name: gen hw report
  hosts: all
  tasks:
  - name: download an empty file
    ansible.builtin.get_url:
      url: http://webserver:8080/hwreport.empty
      dest: /root/hwreport.txt
  - name: report 1
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: "^HOST="
      line: HOST={{ ansible_hostname }}
  - name: report 2
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: "^MEMORY="
      line: MEMORY={{ ansible_memtotal_mb }}
  - name: report 3
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: "^BIOS="
      line: BIOS={{ ansible_bios_version }}
  - name: report 4
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: "^DISK_SIZE_SDA="
      line: DISK_SIZE_SDA={{ ansible_devices.sda.size }}
  - name: report 5
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: "^DISK_SIZE_SDB="
      line: DISK_SIZE_SDB={{ ansible_devices.sdb.size | default('NONE',true) }}
