---
- name: create and use logical volume
  hosts: all
  tasks:
  - block:
    - name: create 1500M
      community.general.lvol:
        vg: research
        lv: data
        size: 1500
    - name: create ext4 fs
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data
    rescue:
    - name: Could not create LVM
      ansible.builtin.debug:
        msg: "Could not create a logical volume at that size"
    - name: create 800M
      community.general.lvol:
        vg: research
        lv: data
        size: 800
    - name: create ext4 fs
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data
    when: ansible_lvm.vgs.research is defined
  - debug:
      msg: "The volume group does not exist"
    when: ansible_lvm.vgs.research is not defined
