---
collections:
- name: http://webserver:8080/redhat-insights-1.0.7.tar.gz
- name: http://webserver:8080/community-general-5.5.0.tar.gz
- name: http://webserver:8080/redhat-rhel_system_roles-1.19.3.tar.gz 
